server: 
  port: 8080
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayService
 cloud:
    gateway:
      routes:
      - id: CustomerService
        uri: http://localhost:8083/
        predicates:
        - Path=/amazon/customers/**
      - id: ProductService
        uri: http://localhost:8092/
        predicates:
        - Path=/amazon/products/**
      - id: JWTService
        uri: http://localhost:8094/
        predicates:
        - Path=/api/jwt/**
      - id: CartService
        uri: http://localhost:8084/
        predicates:
        - Path=/amazon/cart/**